# docker-compose up -d --build

version: '3'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: db
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: comicslib
    volumes:
      - ./db-init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - db_data:/var/lib/mysql
    networks:
      - private

  api:
    build: ./server
    container_name: api
    restart: unless-stopped
    ports:
      - 3001:3001
      - 5555:5555
    expose:
      - 3001
      - 5555 # for prisma studio
    depends_on:
      - db
    environment:
      PORT: 3001
      DATABASE_URL: mysql://root:root@db:3306/comicslib
      CLIENT_DOMAIN: http://localhost:3000
    networks:
      - private
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3001']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # web:
  #   build: ./client
  #   container_name: web
  #   restart: unless-stopped
  #   ports:
  #     - 3000:3000
  #   expose:
  #     - 3000
  #   depends_on:
  #     api:
  #       condition: service_completed_successfully
  #   environment:
  #     PORT: 3000
  #     APP_URL: 'http://localhost:3000'
  #     API_HOST: 'http://api:3001/api'
  #   networks:
  #     - private
  #     - public

volumes:
  db_data:

networks:
  private:
    driver: bridge
  public:
    driver: bridge
